import {defineField, defineType} from 'sanity'
import {DocumentTextIcon} from '@sanity/icons/DocumentText'

// Machine-owned. Metadata uses `readOnly: () => true` (conditional) because
// Agent Actions refuse fields with a literal `readOnly: true`.
export const markdownPage = defineType({
  name: 'markdownPage',
  title: 'Markdown Page',
  type: 'document',
  icon: DocumentTextIcon,
  description: 'Written by the ingest run; manual edits are overwritten.',
  fields: [
    defineField({
      name: 'title',
      type: 'string',
      readOnly: () => true,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'description',
      type: 'text',
      rows: 2,
      readOnly: () => true,
    }),
    defineField({
      name: 'path',
      type: 'string',
      description: 'Site path, e.g. "/about".',
      readOnly: () => true,
      validation: (rule) =>
        rule.required().regex(/^\/(?!.*\.md$)\S*$/, {name: 'site path', invert: false}),
    }),
    defineField({
      name: 'sourceUrl',
      type: 'url',
      readOnly: () => true,
    }),
    defineField({
      name: 'markdown',
      type: 'text',
      rows: 30,
      description: 'Generated by Agent Actions.',
    }),
    defineField({
      name: 'sourceHash',
      type: 'string',
      description: 'Unchanged pages are skipped.',
      readOnly: () => true,
    }),
    defineField({
      name: 'ingestedAt',
      type: 'datetime',
      readOnly: () => true,
    }),
  ],
  orderings: [{title: 'Path', name: 'path', by: [{field: 'path', direction: 'asc'}]}],
  preview: {
    select: {path: 'path', title: 'title', ingestedAt: 'ingestedAt'},
    prepare({path, title, ingestedAt}) {
      const when = ingestedAt
        ? `ingested ${new Date(ingestedAt).toLocaleString()}`
        : 'never ingested'
      return {
        title: path ?? '(no path)',
        subtitle: [title, when].filter(Boolean).join(' · '),
      }
    },
  },
})
